### ISSUE TITLE
PC98 music player error

### ISSUE THREAD

**Issue by pikakid98** [a-digital-project/Touhou-Launcher#1]
Not sure if you're having this problem too but from this screenshot you can see that I'm playing Spirit Battle... right?
![Capture](https://user-images.githubusercontent.com/12392651/162271563-a10afccb-4321-4a11-96cb-0ac5b8aba921.PNG)
Wrong!.. I'm actually playing Bad Apple.. And this seems to be the case for all of the PC-98 games.. not all of them.. Only Touhou 1-5. The screenshot below shows what happens when you try to load the first song..
![Capture2](https://user-images.githubusercontent.com/12392651/162271574-e0ccc798-ddf6-4ee4-ab5b-20471c28f2b1.PNG)
It seems to be attempting to load a non-existant file. I first noticed this error when listening to Touhou 5's Bizarre Romantic Story. However, to load Bizarre Romantic Story I had to click Dream Express.. it seems like the PC-98 music's list has every song bumped down by 1 slot while slot 1 is empty and causes a crash

**Comment by Seraphie** [comment]
This has been fixed by version 4.2.1 released just now, if you have any other problem feel free to open another issue!
