### ISSUE TITLE
THCRAP config keeps getting reset

### ISSUE THREAD

**Issue by pikakid98** [a-digital-project/Touhou-Launcher#2]
For some reason whenever I open the launcher it keeps resetting my THCRAP config file.. or rather the one for the game paths. Whenever I open a game it tells me 
```
Failed to start C:\Users\admin\Desktop\-\= Game Related Stuff\~Non-Steam Game Stuff\- Non-Steam Games\Touhou Project\Game Files\thcrap\Games\Touhou 09 - Phantasmagoria Of Flower View\vpatch.exe
The directory name is invalid.
```
And if I set the directory properly with a "../Games/<game>" path in the game config file then it gets reset upon relaunching the launcher.. and I'm pretty sure this isn't a problem with thcrap

**Comment by Seraphie** [comment]
The launcher rewrites the games.js file and uses the paths of the games within the launcher, it is expected behaviour.

**Comment by pikakid98** [comment]
it would be nice to have an option to disable that though.. just saying..

After typing this I'm now just running the launcher in a seperate subfolder.. in other words
```
Games
Launcher
```

still kind of annoying but not the end of the world, I guess

**Comment by Seraphie** [comment]
Might look into it for a future update, unfortunately that'll have to do for now
